### PR TITLE
Support GX1400 via serial adapter

### PR DESCRIPTION
**Pull request by mbof**
Support GX1400 (#55) via serial adapter.

### CODE REVIEW

**Comment by johannessen** [comment]
I’ll give this another test run with my device for good measure, but it'll take me a couple of days.

**Comment by mbof** [comment]
Sounds good, thank you as always! If you get a chance, this is now on the main version at https://mbof.github.io/hx/. The alpha version is still running behind the last change as of right now.

**Comment by johannessen** [comment]
Yep, 1.3.0 (a5b45f1e4efc80ade55a8391722b9545d293304f) works fine for me.

**Comment by mbof** [comment]
Thanks!

**Comment by johannessen** [comment]
Thank *you* for all your work! ☺️

**Pull request merged**
